// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removerequiredfromgenreproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removerequiredfromgenreproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201809112021066_remove required from genre property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
